modLoader="javafml"
loaderVersion="[4,)"
license="ARR"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="fishing_rod_compat.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tide"
type="required"
versionRange="[2.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aquaculture"
type="required"
versionRange="[2.7.21,)"
ordering="AFTER"
side="BOTH"
